- input:
    Resources:
      table1F1EAFA30:
        Type: AWS::DynamoDB::Table
        Properties:
          KeySchema:
          - AttributeName: table1
            KeyType: HASH
          AttributeDefinitions:
          - AttributeName: table1
            AttributeType: S
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        UpdateReplacePolicy: Retain
        DeletionPolicy: Retain
        Metadata:
          aws:cdk:path: FtCdkDynamoDBStack/table1/Resource
  expectations:
    rules:
      dynamo_db_table_has_sse_turned_on: FAIL
- input: 
    Resources:
      table2KeyE5C30A5F:
        Type: AWS::KMS::Key
        Properties:
          KeyPolicy:
            Statement:
            - Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
              - kms:GenerateDataKey
              - kms:TagResource
              - kms:UntagResource
              Effect: Allow
              Principal:
                AWS:
                  Fn::Join:
                  - ''
                  - - 'arn:'
                    - Ref: AWS::Partition
                    - ":iam::115272120974:root"
              Resource: "*"
            Version: '2012-10-17'
          Description: Customer-managed key auto-created for encrypting DynamoDB table
            at FtCdkDynamoDBStack/table2
          EnableKeyRotation: true
        UpdateReplacePolicy: Retain
        DeletionPolicy: Retain
        Metadata:
          aws:cdk:path: FtCdkDynamoDBStack/table2/Key/Resource
      table2369D7B05:
        Type: AWS::DynamoDB::Table
        Properties:
          KeySchema:
          - AttributeName: table2
            KeyType: HASH
          AttributeDefinitions:
          - AttributeName: table2
            AttributeType: S
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          SSESpecification:
            KMSMasterKeyId:
              Fn::GetAtt:
              - table2KeyE5C30A5F
              - Arn
            SSEEnabled: true
            SSEType: KMS
        UpdateReplacePolicy: Retain
        DeletionPolicy: Retain
        Metadata:
          aws:cdk:path: FtCdkDynamoDBStack/table2/Resource
  expectations:
    rules:
      dynamo_db_table_has_sse_turned_on: PASS
- input: 
    Resources:
      Key961B73FD:
        Type: AWS::KMS::Key
        Properties:
          KeyPolicy:
            Statement:
            - Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
              - kms:GenerateDataKey
              - kms:TagResource
              - kms:UntagResource
              Effect: Allow
              Principal:
                AWS:
                  Fn::Join:
                  - ''
                  - - 'arn:'
                    - Ref: AWS::Partition
                    - ":iam::115272120974:root"
              Resource: "*"
            Version: '2012-10-17'
          EnableKeyRotation: true
        UpdateReplacePolicy: Retain
        DeletionPolicy: Retain
        Metadata:
          aws:cdk:path: FtCdkDynamoDBStack/Key/Resource
      table3D51B311A:
        Type: AWS::DynamoDB::Table
        Properties:
          KeySchema:
          - AttributeName: table3
            KeyType: HASH
          AttributeDefinitions:
          - AttributeName: table3
            AttributeType: S
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          SSESpecification:
            SSEEnabled: true
            KMSMasterKeyId:
              Ref: Key961B73FD
            SSEType: KMS
        UpdateReplacePolicy: Retain
        DeletionPolicy: Retain
        Metadata:
          aws:cdk:path: FtCdkDynamoDBStack/table3/Resource
  expectations:
    rules:
      dynamo_db_table_has_sse_turned_on: PASS
- input:
    Resources: {}
  expectations:
    rules:
      dynamo_db_table_has_sse_turned_on: SKIP
