---
- input:
    Resources: {}
  expectations:
    rules:
      check_rest_api_is_private_and_has_access: SKIP
- input:
    Resources:
      apiGw:
        Type: 'AWS::ApiGateway::RestApi'
  expectations:
    rules:
      check_rest_api_is_private_and_has_access: FAIL
- input:
    Resources:
      apiGw:
        Type: 'AWS::ApiGateway::RestApi'
        Properties:
          EndpointConfiguration: ["PRIVATE"]
          Policy:
            Statement:
              - Action: Allow
                Resource: ['*', "aws:"]
                Condition:
                    'aws:IsSecure': true
  expectations:
    rules:
      check_rest_api_is_private_and_has_access: FAIL
- input:
    Resources:
      apiGw:
        Type: 'AWS::ApiGateway::RestApi'
        Properties:
          EndpointConfiguration: ["PRIVATE"]
          Policy:
            Statement:
              - Action: Allow
                Resource: ['*', "aws:"]
                Condition:
                    'aws:SourceVpc': 'vpc-123456789'
                    'aws:IsSecure': true
  expectations:
    rules:
      check_rest_api_is_private_and_has_access: PASS
