---
- input:
    Resources: {}
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: FAIL
      dynamo_db_table_has_sse_turned_on: FAIL
- input:
    Resources:
      nonCompliant: 
        Type: Consoto::Network::VPC
        Properties: {}
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: FAIL
      dynamo_db_table_has_sse_turned_on: FAIL
- input:
    Resources:
      nonCompliant: 
        Type: Consoto::Network::VPC
        Properties: 
          Tags: []
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: FAIL
      dynamo_db_table_has_sse_turned_on: FAIL
- input:
    Resources:
      nonCompliant: 
        Type: Consoto::Network::VPC
        Properties: 
          Tags: 
            - Key: Hi
              Value: There
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: PASS
      dynamo_db_table_has_sse_turned_on: SKIP # no DDB tables
- input:
    Resources:
      nonCompliant: 
        Type: Consoto::Network::VPC
        Properties: 
          Tags: 
            - Key: Hi
              Value: There
      ddb:
        Type: AWS::DynamoDB::Table
        Properties:
          Tags: 
            - Key: Hi
              Value: There
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: PASS
      dynamo_db_table_has_sse_turned_on: FAIL # does not have SSE set
- input:
    Resources:
      nonCompliant: 
        Type: Consoto::Network::VPC
        Properties: 
          Tags: 
            - Key: Hi
              Value: There
      ddb:
        Type: AWS::DynamoDB::Table
        Properties:
          Tags: 
            - Key: Hi
              Value: There
          SSESpecification:
            SSEEnabled: false
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: PASS
      dynamo_db_table_has_sse_turned_on: FAIL
- input:
    Resources:
      nonCompliant: 
        Type: Consoto::Network::VPC
        Properties: 
          Tags: 
            - Key: Hi
              Value: There
      ddb:
        Type: AWS::DynamoDB::Table
        Properties:
          Tags: 
            - Key: HiPROD
              Value: There
          SSESpecification:
            SSEEnabled: true
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: PASS
      dynamo_db_table_has_sse_turned_on: PASS
- input:
    Resources:
      nonCompliant: 
        Type: Consoto::Network::VPC
        Properties: 
          Tags: 
            - Key: Hi
              Value: There
      ddb:
        Type: AWS::DynamoDB::Table
        Properties:
          Tags: 
            - Key: HiPROD
              Value: There
          SSESpecification:
            SSEEnabled: true
            SSEType: KMS
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: PASS
      dynamo_db_table_has_sse_turned_on: PASS
