business-tax-application:
  Type:  AWS::Application
  Metadata:
    app:
      Type: Intuit::App::Info
      Properties:
        cost-center   : "Intuit-Biz-Tax"
        cti           : "Intuit/Biz/TaxApps"
  Properties:

    parent            : null

    contains          :
      credential-management:
        arn           : !Ref credential-management-stack
        name          : !Ref credential-management-stack.name
        id            : !Ref credential-management-stack.stack-id
      code-setup:
        arn           : !Ref code-repository-stack
        name          : !Ref code-repository-stack.name
        id            : !Ref code-repository-stack.stack-id
      toolchain:
        arn           : !Ref toolchain-pipeline-stack
        name          : !Ref toolchain-pipeline-stack.name
        id            : !Ref toolchain-pipeline-stack.stack-id

    comprises-of      :
      - !Ref beta-stage-application
      - !Ref gamma-stage-application
      - !Ref prod-stage-application

credential-management-stack:
  Type: AWS::CloudFormation::Stack
  Properties:


Parameters:
  GitHubServiceUser:
    Type: String
    NoStore: true *(TBD)*
  GitHubOAuthToke:
    Type: String
    NoStore: true *(TBD)*
Resources:
  github-oauth:
    Type: AWS::SecretsManager::SetupOAuthModule
    Properties:
      user          : !Ref GitHubServiceUser
      oauth-token   : !Ref GitHubOAuthToken

toolchain-pipeline-stack:
  Type: AWS::CloudFormation::Stack
  Properties:


Resources:
  code-pipeline:
    Type: AWS::CodePipeline::StandardBetaGammaProdModule
    Properties:
      build-repo:
        GitHub:
          access: !Ref credential-management-stack.github-oauth.arn
      beta:
        environment:
          ..
          ..
        deploy:
          stack-name: !Ref beta-stage-application.contains.app.name
      gamma:
        environment:
          ..
          ..
        deploy:
          stack-name: !Ref gamma-stage-application.contains.app.name
      prod:
        environment:
          ..
          ..
        deploy:
          stack-name: !Ref prod-stage-application.contains.app.name

beta-stage-application:
  Type: AWS::Application
  Metadata:
    stage:
      Type: Intuit::App::StageInfo
      Properties:
        name: Beta
  Properties:
    parent            : !Ref business-tax-application.id
    contains          :
      app:
        arn           : !Ref app-setup-stack
        name          : !Ref app-setup-stack.name
        id            : !Ref app-setup-stack.stack-id

app-setup-stack:
  Type: AWS::CloudFormation::Stack
  Properties:
    s3                : s3://location-of-common-definition

code-repository-stack:
  Type: AWS::CloudFormation::Stack
  Properties:

Resources: *(TBD)*
  github:
    Type: GitHub::Repository
    Properties:
      repo-name     : "biz-tax-repo",
      org-name      : "intuit",
      actions       :
        on-push        :   ....
        on-pull-merge  :
          # property access relationship
          web-hook     :
            endpoint      : toolchain-pipeline-stack.code-pipeline.endpoint
          # it can also be modeled as connect-to relationship which can
          # setup API access credentials as well
          # web-hook  := connect-to(toolchain-pipeline-stack.code-pipeline.endpoint)